syntax = "proto3";

message MsgIndicatorCommandOn
{
}

message MsgIndicatorCommandOff
{
}

message MsgIndicatorCommandToggle
{
}

message MsgIndicatorCommandPulse
{
}

message MsgIndicatorCommandGetPulseConfig
{
}

message MsgIndicatorCommandSetPulseConfig
{
	uint32 duration = 1;
}

message MsgIndicatorCommand
{
	oneof indicator_cmd
	{
		MsgIndicatorCommandOn on = 1;
		MsgIndicatorCommandOff off = 2;
		MsgIndicatorCommandToggle toggle = 3;
		MsgIndicatorCommandPulse pulse = 4;
		MsgIndicatorCommandGetPulseConfig get_pulse_config = 5;
		MsgIndicatorCommandSetPulseConfig set_pulse_config = 6;
	}
}

message MsgIndicatorResponseState
{
	bool is_on = 1;
}

message MsgIndicatorResponsePulseConfig
{
	uint32 duration = 1;
}

message MsgIndicatorResponse
{
	oneof indicator_rsp
	{
		MsgIndicatorResponseState state = 1;
		MsgIndicatorResponsePulseConfig pulse_config = 2;
	}
}

message MsgIndicatorEventInitiated
{
}

message MsgIndicatorEventReady
{
}

message MsgIndicatorEventFailed
{
	int32 error_code = 1;
}

message MsgIndicatorEvent
{
	oneof indicator_evt
	{
		MsgIndicatorEventInitiated initiated = 1;
		MsgIndicatorEventReady ready = 2;
		MsgIndicatorEventFailed failed = 3;
	}
}
