CONFIG_ESP_SPIRAM=y
# CONFIG_SPIRAM_MODE_OCT=y
CONFIG_ESP32S3_DATA_CACHE_64KB=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=32768
CONFIG_APP_ALLOC_SPIRAM=n
# CONFIG_ESP32_WIFI_NET_ALLOC_SPIRAM=n

CONFIG_POWER=n
CONFIG_POWER_METER_DRIVER=n
CONFIG_ADE9153A=n
CONFIG_SENSOR=n
CONFIG_PM=n

