# SPIRAM configuration
CONFIG_ESP_SPIRAM=y
CONFIG_ESP32S3_DATA_CACHE_64KB=y
# CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
# CONFIG_SPIRAM_RODATA=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=524288
CONFIG_ESP32_WIFI_NET_ALLOC_SPIRAM=y
CONFIG_ESP_SPIRAM_MEMTEST=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_SPEED_120M=y
CONFIG_MBEDTLS_HEAP_CUSTOM_SECTION=y
