syntax = "proto3";

import "nanopb.proto";

option (nanopb_fileopt).anonymous_oneof = true;

message Indicator {
    message Cmd {
        message On {}

        message Off {}

        message Toggle {}

        message Pulse {}

        message GetConfig {}

        message SetConfig {
            uint32 duration = 1;
        }

        oneof indicator_cmd {
            On on = 1;
            Off off = 2;
            Toggle toggle = 3;
            Pulse pulse = 4;
            GetConfig get_config = 5;
            SetConfig set_config = 6;
        }
    }

    message Evt {
        message State {
            bool is_on = 1;
        }

        message Config {
            uint32 duration = 1;
        }

        oneof indicator_rsp {
        }
        message Initiated {}

        message Ready {}

        message Failed {
            int32 error_code = 1;
        }

        oneof indicator_evt {
            State state = 1;
            Config config = 2;
            Initiated initiated = 3;
            Ready ready = 4;
            Failed failed = 5;
        }
    }
}
